source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-remote-theme", "~> 0.4"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end
